# Generated by Django 3.1.7 on 2021-03-26 19:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelID', models.PositiveIntegerField(default=0, editable=False)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('travelsOrigins', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, size=None)),
                ('travelsDestination', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, size=None)),
            ],
        ),
    ]
