# Generated by Django 3.1.6 on 2021-03-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchResults', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplan',
            old_name='destinationCountry',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='travelplan',
            old_name='originCountry',
            new_name='origin',
        ),
    ]
