# Generated by Django 3.2 on 2021-04-14 06:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchResults', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='travelsDestination',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='travelsOrigins',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='travelDestination',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='travelOrigins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='travelID',
            field=models.PositiveIntegerField(default=0, editable=False, unique=True),
        ),
    ]
